version: "3.9"

services:
  web:
    container_name: web
    build: .
    ports:
      - 8080:8080
    environment:
      - VUE_APP_API_URL=https://api.pdl-dev.local.epay.vn
      - VUE_APP_SANDBOX_API_URL=https://epay.sandbox.integreat.perfios.com
      - VUE_APP_PRODUCTION=false
      - VUE_APP_SENTRY_DSN=https://13f18b48c55246a2a3d65a3572b3cea5@o818430.ingest.sentry.io/5807970
      - VUE_APP_PARTNER=tn
      - VUE_APP_CONTRACT_UUID=fe6af646-42ba-4433-90cb-108acaba7543
      - VUE_APP_ACTIVITY_STATUS=acceptContract
      - VUE_APP_ZALO_URL=https://zalo.me/2848902721585176437
      - VUE_APP_FB_MESSENGER_URL=https://m.me/monexvn
      - VUE_APP_GUIDE_VIDEO_URL=https://youtu.be/sGM98Ot89TE
      - VUE_APP_MAINTAIN=false
      - VUE_APP_API_CORE_URL=https://api.pdl-dev.local.epay.vn/core
      - VUE_APP_CUSTOMER_API_URL=https://api.pdl-dev.local.epay.vn/customer
      - VUE_APP_LOANAPP_API_URL=https://api.pdl-dev.local.epay.vn/loanapp
      - VUE_APP_PAYMENT_API_URL=https://api.pdl-dev.local.epay.vn/payment
      - VUE_APP_COM_API_URL=https://api.pdl-dev.local.epay.vn/com
      - VUE_APP_CONTRACT_API_URL=https://api.pdl-dev.local.epay.vn/contract
      - VUE_APP_IDENTITY_API_URL=https://api.pdl-dev.local.epay.vn/identity
      - VUE_APP_COMPANY_ID=7d2ce511-f4f6-4eff-9771-1e7b02e0838e
      - VUE_APP_ENV=dev
      - VUE_APP_PAYMENT_ORDER_NAME=PaydayLoan-TNG
