import i18n from "../lang/i18n";

export const MODAL_TYPE = {
  LOGIN: "login-register",
  FORGOT_PASSWORD: "forgot-password",
  FORGOT_PASSWORD_OTP: "forgot-password-otp",
  SIGNUP_OTP: "signup-otp",
  PL_SUCCESS: "payday-loan-success",
  PL_SUCCESS_NOTIFICATION: "payday-loan-success-notification",
  PL_ERROR: "payday-loan-error",
  PL_WAITING: "payday-loan-waiting",
  PL_FAILED: "payday-loan-failed",
  PL_NOT_EMPLOYEE: "payday-loan-not-employee",
  PL_CHOOSE_VOUCHER: "payday-loan-choose-voucher",
  PL_TYPE_OTP: "payday-loan-type-otp",
  PL_ELECTRONIC_SINGING: "payday-loan-electronic-signing",
  PL_ADS: "payday-loan-ads",
  PL_SIGN_APPROVAL_LETTER_SUCCESS: "payday-loan-sign-approval-letter-success",
  PL_GUIDE_SIGN_CONTRACT: "payday-loan-guide-sign-contract",
  PL_GUIDE_SIGN_LETTER_TERM_OF_SERVICE:
    "payday-loan-guide-sign-letter-term-of-service",
  PL_COLLATERAL_DOCUMENT_EXAMPLE: "payday-loan-collateral-document-example",
  PL_SALARY_DOCUMENT_EXAMPLE: "payday-loan-salary-document-example",
  PL_CONFIRM_FINALIZATION: "payday-loan-confirm-finalization",
  PL_GUIDE_TRANSFER_PAYMENT: "payday-loan-guide-transfer-payment",
  PL_RATING: "payday-loan-rating",
  PL_CHOOSE_OTP_METHOD: "payday-loan-choose-otp-method",
};

export const PAYDAY_LOAN_STEP = {
  ELECTRONIC_IDENTIFIERS: 1,
  CONFIRM_INFORMATION: 2,
  ADDITIONAL_INFORMATION: 3,
  CHOOSE_AMOUNT_TO_BORROW: 4,
  CONTRACT_SIGNING: 5
};

export const LABEL_STATUS = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  DISBURSEMENT: "DISBURSEMENT",
  REJECT: "REJECT",
  CANCEL: "CANCEL"
};

export const PAYDAY_LOAN_STATUS = {
  NOT_VERIFY_YET: "NOT_VERIFY_YET",
  FUNDED: "FUNDED",
  DOCUMENT_AWAITING: "DOCUMENT_AWAITING",
  INITIALIZED: "INITIALIZED",
  AWAITING_APPROVAL: "AWAITING_APPROVAL",
  DOCUMENTATION_COMPLETE: "DOCUMENTATION_COMPLETE",
  REJECTED: "REJECTED",
  WITHDRAW: "WITHDRAW",
  AUCTION: "AUCTION",
  CONTRACT_ACCEPTED: "CONTRACT_ACCEPTED",
  AWAITING_DISBURSEMENT: "AWAITING_DISBURSEMENT",
  DISBURSED: "DISBURSED",
  IN_REPAYMENT: "IN_REPAYMENT",
  COMPLETED: "COMPLETED",
  OVERDUE_L2: "OVERDUE_L2",
  CONTRACT_REJECTED: "CONTRACT_REJECTED",
  UNKNOWN_STATUS: "UNKNOWN_STATUS",
  CALLBACK_PAYMENT_RESULT: "CALLBACK_PAYMENT_RESULT"
};

export const PAYDAY_LOAN_UI_STATUS = {
  NOT_COMPLETE_EKYC_YET: "NOT_COMPLETE_EKYC_YET",
  NOT_COMPLETE_FILL_EKYC_YET: "NOT_COMPLETE_FILL_EKYC_YET",
  NOT_ACCEPTING_TERM_YET: "NOT_ACCEPTING_TERM_YET",
  NOT_COMPLETE_CDE_YET: "NOT_COMPLETE_CDE_YET",
  COMPLETED_CDE: "COMPLETED_CDE"
};
export const PAYDAY_LOAN_UI_STATUS_ORDER_NUMBER = {
  NOT_COMPLETE_EKYC_YET: 1,
  NOT_COMPLETE_FILL_EKYC_YET: 2,
  NOT_ACCEPTING_TERM_YET: 3,
  NOT_COMPLETE_CDE_YET: 4,
  COMPLETED_CDE: 5
};

export const PAYDAY_LOAN_STATUS_PAGE = {
  NOT_COMPLETE_EKYC_YET: "PlEKYC",
  NOT_COMPLETE_FILL_EKYC_YET: "PlConfirmInformation",
  NOT_ACCEPTING_TERM_YET: "PlContractTermsOfService",
  NOT_COMPLETE_CDE_YET: "PlAdditionalInformation",
  COMPLETED_CDE: "PlChooseAmountToBorrow"
};

export const PL_MESSAGE_TYPE = {
  SUCCESS: "SUCCESS",
  INFORMATION: "INFORMATION",
  WARNING: "WARNING"
};

export const PL_VALUE_DEFAULT = {
  STEP_VALUE: 500000,
  MIN_VALUE: 2000000,
  MAX_VALUE: 10000000,
  MIN_SERVICE_FEE: 100000,
  FIXED_REPAYMENT_GPAY_FEE: 1650,
  FIXED_REPAYMENT_GPAY_DYNAMIC: 1.1,
  FIXED_REPAYMENT_VA_FEE: 3500,
  FIXED_DISBURSEMENT_FEE: 7700,
  VAT_FEE_PERCENT: 0.1,
  SERVICE_FEE_RATIO: 0.025,
  MAX_RESEND_OTP: 3,
  MAX_TYPE_WRONG_OTP: 2,
  RESEND_OTP_COUNTDOWN_TIME: 60,
  REDIRECT_TO_SIGN_IN_COUNTDOWN_TIME: 5,
  LOAN_PAYMENT_SUBMIT_COUNTDOWN_TIME: 30,
  PERCENT_OF_SALARY: 80 / 100,
  UNIX_TIMESTAMP_SAVE_EKYC_INFO: 6 * 30 * 24 * 60 * 60 * 1000,
  OPEN_DATE: 16,
  CLOSE_DATE: 16,
  LOCKED_SEND_OTP_SIGN_CONTRACT_TERMS_MINUTES: 30,
  LOCKED_SEND_OTP_SIGN_CONTRACT_MINUTES: 30,
  MAX_TYPE_WRONG_OTP_SIGN_CONTRACT_TIMES: 5,
  MAX_TYPE_WRONG_OTP_SIGN_CONTRACT_TERMS_TIMES: 5,
  PHONE_NUMBER_WHITE_LIST_PATTERN: /^01/,
  COUNTDOWN_TIME: "2021-09-30 06:00:00",
  COUNTDOWN_START_TIME: "2021-09-29 18:00:00",
  CLOSE_ADS_POPUP_TIME: "2021-10-17 23:59:59",
  OPEN_ADS_POPUP_TIME: "2021-10-10 00:00:01"
};

export const WRONG_OTP_TYPE = {
  SIGN_CONTRACT: "contract",
  SIGN_CONTRACT_TERMS: "contractTerms"
};

export const COMMON_PROPERTIES = {
  GENDER: "GENDER",
  MARITAL_STATUS: "MARITAL_STATUS",
  EDUCATION_TYPE: "EDUCATION_TYPE",
  NUMBER_OF_DEPENDENTS: "BORROWER_DETAIL_VARIABLE1",
  BORROWER_EMPLOYMENT_HISTORY: "BORROWER_EMPLOYMENT_VARIABLE1"
};


export const DOCUMENT_TYPE = {
  ID_CARD: "ID_CARD",
  FRONT_ID_CARD: "FRONT_ID_CARD",
  BACK_ID_CARD: "BACK_ID_CARD",
  SELFIE: "SELFIE",
  BANK_BOOK: "BANK_BOOK",
  PAY_SLIP: "PAY_SLIP",
  UN_KNOWN: "UN_KNOWN",
  CONTRACT: "CONTRACT",
  LETTER_OF_ACCEPTANCE: "LETTER_OF_ACCEPTANCE",
  VEHICLE_REGISTRATION: "VEHICLE_REGISTRATION",
  SALARY_INFORMATION_ONE: "SALARY_INFORMATION_ONE",
  SALARY_INFORMATION_TWO: "SALARY_INFORMATION_TWO",
  SALARY_INFORMATION_THREE: "SALARY_INFORMATION_THREE"
};

export const ERROR_CODE = {
  ACCOUNT_EXISTED: "ACCOUNT_EXISTED",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  ACCOUNT_NOT_EXIST: "ACCOUNT_NOT_EXIST",
  MISS_PARAM: "MISS_PARAM",
  DATA_ERROR: "DATA_ERROR",
  WRONG_PASSWORD: "WRONG_PASSWORD",
  OTP_EXPIRE_TIME: "OTP_EXPIRE_TIME",
  OTP_INVALID: "OTP_INVALID",
  OTP_CONFIRM_MAXIMUM: "OTP_CONFIRM_MAXIMUM",
  SESSION_SIGN_ALREADY_EXIST: "SESSION_SIGN_ALREADY_EXIST",
  LOCK_CREATE_NEW_SESSION: "LOCK_CREATE_NEW_SESSION",
  DO_NOT_EXIST_VIRTUAL_ACCOUNT: "DO_NOT_EXIST_VIRTUAL_ACCOUNT",
  NOT_CURRENT_LOAN_REPAYMENT_ERROR: "NOT_CURRENT_LOAN_REPAYMENT_ERROR",
  ZALO_OTP_ERROR: "ZALO_OTP_ERROR"
};

export const ERROR_CODE_TEXT = {
  ACCOUNT_EXISTED: i18n.t("payday_loan.error_code.account_existed"),
  EMAIL_ALREADY_EXISTS: i18n.t("payday_loan.error_code.email_already_exits"),
  ACCOUNT_NOT_EXIST: i18n.t("payday_loan.error_code.account_not_exist"),
  MISS_PARAM: i18n.t("payday_loan.error_code.miss_param"),
  DATA_ERROR: i18n.t("payday_loan.error_code.data_error"),
  WRONG_PASSWORD: i18n.t("payday_loan.error_code.wrong_password"),
  OTP_EXPIRE_TIME: i18n.t("payday_loan.error_code.otp_expire_time"),
  OTP_INVALID: i18n.t("payday_loan.error_code.otp_invalid"),
  OTP_CONFIRM_MAXIMUM: i18n.t("payday_loan.error_code.otp_confirm_maximum"),
  SESSION_SIGN_ALREADY_EXIST: i18n.t(
    "payday_loan.error_code.session_sign_already_exist"
  ),
  LOCK_CREATE_NEW_SESSION: i18n.t(
    "payday_loan.error_code.lock_create_new_session"
  ),
  ZALO_OTP_ERROR: i18n.t("payday_loan.error_code.zalo_otp_error")
};

export const GPAY_RESULT_STATUS = {
  ORDER_PENDING: "ORDER_PENDING",
  ORDER_PROCESSING: "ORDER_PROCESSING",
  ORDER_SUCCESS: "ORDER_SUCCESS",
  ORDER_FAILED: "ORDER_FAILED",
  ORDER_CANCEL: "ORDER_CANCEL",
  ORDER_VERIFYING: "ORDER_VERIFYING"
};

export const REPAYMENT_STATUS = {
  OVERDUE: "OVERDUE"
};

export const SIGN_STATUS = {
  ACCEPTED: "ACCEPTED",
  AWAITING_BORROWER_SIGNATURE: "AWAITING_BORROWER_SIGNATURE",
  AWAITING_EPAY_SIGNATURE: "AWAITING_EPAY_SIGNATURE",
  DONE: "DONE"
};

export const APPLICATION_TYPE = {
  PAYDAYLOAN_TNG: "PaydayLoan-TNG",
  PAYDAYLOAN_HMG: "PaydayLoan-HMG",
  INSURANCE: "Insurance"
};

export const RATE_VALUE = {
  NOT_SATISFIED: "NOT_SATISFIED",
  SEMI_SATISFIED: "SEMI_SATISFIED",
  NORMAL: "NORMAL",
  SATISFIED: "SATISFIED",
  VERY_SATISFIED: "VERY_SATISFIED"
};
export const RATING_APPLICATION_TYPE = {
  PDL_TNG: "PDL_TNG",
  PDL_HMG: "PDL_HMG",
  INSURANCE: "INSURANCE"
};

export const OTP_TYPE = {
  EMAIL: "EMAIL",
  SMS: "SMS",
  VOICE: "VOICE"
};

export default {
  MODAL_TYPE,
  PAYDAY_LOAN_STEP,
  PAYDAY_LOAN_STATUS,
  PAYDAY_LOAN_UI_STATUS,
  PL_MESSAGE_TYPE,
  PL_VALUE_DEFAULT,
  COMMON_PROPERTIES,
  DOCUMENT_TYPE,
  LABEL_STATUS,
  ERROR_CODE,
  ERROR_CODE_TEXT,
  GPAY_RESULT_STATUS,
  OTP_TYPE,
  WRONG_OTP_TYPE,
  SIGN_STATUS,
  REPAYMENT_STATUS,
  APPLICATION_TYPE,
  RATE_VALUE,
  RATING_APPLICATION_TYPE
};
